# 注意保持TOML文件格式（等号两边有空格）
DEEPSEEK_API_KEY = "sk-13fe07aa27534e458bc241ab23bc6e9b"
DEEPSEEK_BASE_URL = "https://api.deepseek.com/beta"
QWEN_API_KEY = "sk-68fd531c27e74f83ac79a81a3eb67e45"
QWEN_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"